# Generated by Django 5.0 on 2023-12-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название товара/услуги')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Изображение товара/услуги')),
                ('description', models.TextField(verbose_name='Описание товара/услуги')),
            ],
            options={
                'verbose_name': 'Товар/Услуга',
                'verbose_name_plural': 'Товары/Услуги',
            },
        ),
    ]
