# Generated by Django 5.0 on 2023-12-26 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_advuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdvUser',
        ),
    ]
