# Generated by Django 5.0 on 2023-12-26 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_userprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
